### ISSUE TITLE
How to? Inter-isolate communication

### ISSUE THREAD

**Issue by NightOwlCoder** [krista-koivisto/isolate_handler#13]
Hey there,
this is the sentence that attracted me to this package:

>Effortless isolates abstraction layer with support for inter-isolate communication. 

But I can't make the `inter-isolate communication` work.

I've 2 isolates that I need to send message between them for some synchronization.
At this point, just send, without receive would be good enough...

Any samples?

**Comment by youssef-fk** [comment]
Looking for a solution for this as well

**Comment by deakjahn** [comment]
This issue probably comes from the era when GitHub didn't send me notifications for some unknown reason because I never saw it. Sorry.

You should be able to send messages with ease. The `to` argument of the`send()` function allows you to use the name you assigned to the isolate to tell it which one to send the message to.

**Comment by youssef-fk** [comment]
I don't believe we could do that, could please give more clarification, here is where i'm having an issue.

Isolates don't share memory with each other. So we can't access the same instance of `IsolateHandler`.

Inside the `_entryPoint` method, we have a `messenger` which is an instance of `HandledIsolateMessenger`, the `send` method of this object doesn't contain a `to` argument.

**Comment by deakjahn** [comment]
OK, I can see your problem now. Let me see because I have an app where I upload file packages in isolates (each has its own isolate to make them independent and, possible, parallel), but I wrote it some time ago and didn't need to revisit this part since.

In this case, I have a separate class (you can make it a singleton) that encloses the necessary items and functions:

* the `IsolateHandler`
* a map of `<String, IsolateHandlerMessenger>`
* helper functions like `sendTo(name, message)`, `sendFrom(name, message)`

The first is very simple:

    void sendTo(String name, dynamic message) {
      _isolates.send(message, to: name);
    }

The second is a bit more tricky. When I start the listening, I store the messenger:

    _messengers[name] = HandledIsolate.initialize(context);

and then I can use the name to look it tup:

    void sendFrom(String name, dynamic message) {
      final messenger = _messengers[name];
      assert(messenger != null, 'Unknown name');
  
      messenger.send(message);
    }

I can also have other helpers like `kill(name)` and similar, they're trivial.

I actually use this central class to handle all my communication (both to and from the isolates).

**Comment by youssef-fk** [comment]
I think I understand better now. 

Essentially we are sending the data via the `onReceive` callback . So data flows from isolate, to main thread, to another isolate.

This will be completely valid for an app that is in its `Foreground State`. What I wanted to achieve was inter-communication while the app is in background state. I don't believe this would be achievable, since the 'onReceive' callback wouldn't fire until the app is resumed. Do you agree ?

I think the best way to resolve this is, have my background state run in a single isolate, so I will be able to share memory, since my concern is not with performance but with background activity.

**Comment by deakjahn** [comment]
This is something that should be tried in practice. With my setup described above, an isolate can simply send a message to another isolate, provided it knows the name of the second isolate. But you need to try it, I don't think I needed anything similar in my apps.

**Comment by jayjah** [comment]
@youssef-fk Actually it should work, when you mean with a background state a real background state and NOT a suspended one (e.g. ios https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle). Isolate itself runs as long as you kill it or or the app died, it does not depend on the app state itself. But bear in mind this only applies to mobile flutter applications. Web flutter applications are different in their isolate/worker implementation and should be considered differently. Plus keep in mind, a mobile application is not allowed to take to much ram when it's in background and therefore any isolate you create you will need more ram this could be a problem on low android devices...
