### ISSUE TITLE
got 'Unhandled Exception' when send custom object

### ISSUE THREAD

**Issue by ultiwill** [krista-koivisto/isolate_handler#16]
When I send like this:
```
class IsolateMsg<T> {
  final int type;
  final T data;
  IsolateMsg({this.type, this.data});
}
```

`messenger.send(IsolateMsg<bool>(type: 1, data: false));`

I got:

`Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)`

**Comment by deadsoul44** [comment]
@deakjahn I also got this error. Plain Dart Isolates allow custom objects. This is necessary to serialize/deserialize objects in isolates.

**Comment by deakjahn** [comment]
Dear me, GitHub failed to notify me about the OP. :-( Could we come up with a simple sample to reproduce?

**Comment by deadsoul44** [comment]
It is very easy if you have a running example. Just try to send an object with a complex type or the above one.

**Comment by deakjahn** [comment]
`SendPort` is very strict about what it allows and custom types are not among those possible: https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html

This is why we had to change to sending a map during initialization, too. Your only chance is to send a map, and even that only if the actual contents folllow these strict rules. For anything more complicated, you have to use your own serialization to the supported types, practically, string.

**Comment by deadsoul44** [comment]
I am able to send complex objects with plain Isolate. `compute` function is also able to do it. 

```dart
class CustomObject {
  List<DocumentSnapshot> docs;
  SendPort sendPort;

  CustomObject(this.docs, this.sendPort);
}

void isolateFunction(CustomObject customObject) async {
  await debugPrint("isolateFunction...");
  await customObject.sendPort.send(processMyDocs(customObject.docs));
}
```

`processMyDocs` function returns another complex object.

**Comment by deadsoul44** [comment]
> In the special circumstances when two isolates share the same code and are running in the same process (e.g. isolates created via Isolate.spawn), it is also possible to send object instances (which would be copied in the process). This is currently only supported by the Dart Native platform.

**Comment by deakjahn** [comment]
Yes, in those cases, you might. But that's not available to us, mere mortals. :-)

If you check it out, `entryPoint()` now expects to receive a map, even if it only actually contains just a name string and a `SendPort`. Both are on the accepted list, by themselves, but not as a simple data class having these two members. A previous version of this plugin could still use an object here because Krista, when she started this plugin, used a different approach for the communication (remember that this plugin actually has **two** purposes, one is to make it easier to handle isolates and communicate with them, the second is to make it possible to use platform plugins from the isolate; quite a few of us, inlcuding myself, mainly use it because of this second feature, and the ease of handling is just an added bonus).

So, when I jumped on board, it was just because the previous method of handling platform plugin communication was rendered impossible by some internal changes in the Flutter framework, and it seemed completely impossible to salvage the older approach. Then we realized that `flutter_isolate`, another package that only deals with that platform communication side, is still working because it used a completely different approach from the beginning. So, I modified this plugin to rely on `flutter_isolate` while keeping the added features of easier handling and communication between the main isolate and the handled one.

All this boils down to the fact that we're constrained with more than one constraints now, and in order to fulfill _both_ our goals, and relying on `flutter_isolate` as the only viable approach now, I don't think I can promise any modification in this regard. What I can do is to add a comment to the call to draw attention to this limitation and link to the appropriate doc page.
