### ISSUE TITLE
How can I pass the main thread's object or data in isolate content?

### ISSUE THREAD

**Issue by winsonet** [krista-koivisto/isolate_handler#2]
for example, I want to read/write the sqlite data in isolate function, and I have a global database object, I want to pass this into isolate and run it

I also tried to create the database object in `entryPoint` method,

```
messenger.listen((data) {
     var db = InitDB();
}
```

 but when I access the db object and get data, it show me below error:

```
native function 'Window_sendPlatformMessage' (4 arguments) cannot be found
```

I did't use the `channel` for this, so I also want to know can I pass the main thread's data from `channel` ?

thanks!

**Comment by raccoons-are-goofy** [comment]
You can't pass objects between isolates in Flutter, only simple data, so there's no way for you to pass the main thread to your isolate. As for why you get the `sendPlatformMessage` error, it's likely because whatever sqlite plugin you use uses its own isolates internally.

For example [sqflite does for sure](https://stackoverflow.com/a/57478259/11572856). In that case you don't need to make your own isolate. :) If you still want it to start in an isolate, you need to find out which channels the plugin uses and make Isolate Handler aware of them by passing them.

It's also worth mentioning is that any code performed on the native side by the plugin will run on the main (UI) thread, so it will still lock the application. Also, be careful with channels and Isolate Handler, especially with DBs involved. It doesn't always handle multiple concurrent calls well and race conditions can appear, which can lead to unexpected behavior.

**Comment by winsonet** [comment]
I see, thanks for your reply! I just wonder whether flutter can do the synchronize job like google driver in background process, this is what I want to do, or do you have any suggestions for this?

should I use compute for that?

thanks a lot!
