### ISSUE TITLE
how is it possible to work with objects, and not just primitives?

### ISSUE THREAD

**Issue by matejthetree** [krista-koivisto/isolate_handler#22]
When working with `compute` abstraction from dart, you can receive custom objects.

also in the documentation of the `SendPort` it says

> In the special circumstances when two isolates share the same code and are running in the same process (e.g. isolates created via Isolate.spawn), it is also possible to send object instances (which would be copied in the process). This is currently only supported by the Dart Native platform.

Is it possible to achieve the same with isolate_handler

**Comment by moda20** [comment]
i think, no. isolate handler launches a headless flutter, which is another isolate running on a different process so that condition doesn't apply.
what you can do is serialize and deserialization of your object instances. Convert your object to JSON string before sending, and then parse the JSON string on the other hand. you can use other serialization methods for better performance if u can.

**Comment by matejthetree** [comment]
thx. If I understand correctly, the only way for plugins to work is to have them in another process, and compute function creates another thread in the same process?

Unfortunately, we have very large complicated lists computing in the background, so serialization is not an option
