### ISSUE TITLE
Add option to kill immediately

### ISSUE THREAD

**Issue by BernardinD** [krista-koivisto/isolate_handler#25]
First off, this package has been very useful!!! So thank you.

So, would it be possible to add the option to kill immediately?

The original Isolate in flutter has that option and it would be useful for my situation. I believe the currently setup has it where the isolate dies whenever it is done with the current operation it's running. In my case its running a hefty computation

**Comment by deakjahn** [comment]
Is this something `isolates.kill("name");` doesn't provide?

**Comment by BernardinD** [comment]
@deakjahn I don't believe so. It seems `isolates.kill("name")` currently only does the default `isolate.kill()`,  which does `beforeNextEvent`, not `immediate`

[Source](https://api.flutter.dev/flutter/dart-isolate/Isolate/kill.html)

**Comment by deakjahn** [comment]
About a year ago we switched to using `flutter_isolate` instead of handling the isolates ourselves (something has changed in the way Flutter does this and it was better to rely on a package that used another, still functional approach than to replicate all that for ourselves). So, this is twofold now: on one hand, we can only call the methods that `flutter_isolate` actually exposes, and I can't see anything but that only `kill()` there. On the other hand, it seems to me, that it does murder it in the native case:

    void kill() => _isolateId != null
        ? _control.invokeMethod("kill_isolate", {"isolate_id": _isolateId})
        : Isolate.current.kill();

where you can see in the underlying native code on either Android or iOS. However, in the else branch here, yes, there is no priority passed.

So, what I could suggest is that you bring this up at `flutter_isolate` and if they have nothing against adding that default argument to their `kill()`, I'm quite willing to modify this code to pass it along.

**Comment by deakjahn** [comment]
@BernardinD Let's see: https://github.com/rmawatson/flutter_isolate/pull/92

**Comment by deakjahn** [comment]
@BernardinD It took some time for that preview version to be released in full but let's see. 1.0.1 was published with https://github.com/deakjahn/isolate_handler/blob/d514f5cc75a3d5a54f7978b58cf8bc53b5b84df2/lib/isolate_handler.dart#L209
